[package]
name = "dusk-hamt"
version = "0.3.0"
authors = ["Kristoffer Str√∂m <kristoffer@dusk.network>"]
edition = "2018"
description = "HAMT datatructure for microkelvin"
license = "MPL-2.0"
repository = "https://github.com/dusk-network/dusk-hamt"
keywords = ["merkle", "datastructure", "hamt"]

[dependencies]
microkelvin = "0.7"
canonical = "0.6"
canonical_derive = "0.6"
